batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202404211450
train_epochs: 1000
train_workers: 20
vocab: xh:DgNrp3*2&oPn")zdvbcTW5wl1jVX!F6EA8e0(Z/s;kq7ta,KQCuH+B9'y-YIf.S#GJiM RLm4OU?
width: 1408
