batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202404212323
train_epochs: 140
train_workers: 20
vocab: )k/UsO?3:iDmfjQP yH;'Ku8(ar#hdxV,BvJZb0c*lRMS.9pwCnGT-42NzI1EYeLtFg&!o7qAX6+"5W
width: 1408
