batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202404220023
train_epochs: 35
train_workers: 20
vocab: L0wvbDzKF!ln:gsMUQe,IR.6S7OxP"oiYmk1#tTV5&jWCJG+-2) ?9N43q(ycahrp'AH8;/BXEdZfu*
width: 1408
