batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202404212329
train_epochs: 50
train_workers: 20
vocab: :tpy dPi*w76L#frT0hZK;W,IMxY8C1kl!c'N9BU"+AV&z4vOo3s/QG?5(HaueRnDX2FJbgm-q).jSE
width: 1408
