batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202404211452
train_epochs: 1000
train_workers: 20
vocab: /:w0lE2BGxv'*AnX&pMZ(fK,ty"3zWOjVHmqDoR5Fc;L 69Iue.41dY!PrJi-SQkNhC)#?T7Ubags+8
width: 1408
