batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202404212324
train_epochs: 140
train_workers: 20
vocab: 0&BPmob8N1TYiMSGJ+XF94h,".DWZeEk/g;dqa*A'wIst635VQ(fOKU!ucp x7zHR-?2lCv)nrj:Ly#
width: 1408
